//priority: 50

// --------------------------------------- //
// Globals to be used for any script type  //
// --------------------------------------- //

global.CUSTOM_WOOD_TEXTURES = {
    "log_top": {
        "weeping_gala": "spectrum:block/weeping_gala_log_top",
        "slate_noxwood": "spectrum:block/slate_noxcap_stem_top",
        "chestnut_noxwood": "spectrum:block/chestnut_noxcap_stem_top",
        "ivory_noxwood": "spectrum:block/ivory_noxcap_stem_top",
        "ebony_noxwood": "spectrum:block/ebony_noxcap_stem_top",
        "white": "spectrum:block/white_log_top",
        "light_gray": "spectrum:block/light_gray_log_top",
        "gray": "spectrum:block/gray_log_top",
        "black": "spectrum:block/black_log_top",
        "brown": "spectrum:block/brown_log_top",
        "red": "spectrum:block/red_log_top",
        "orange": "spectrum:block/orange_log_top",
        "yellow": "spectrum:block/yellow_log_top",
        "lime": "spectrum:block/lime_log_top",
        "green": "spectrum:block/green_log_top",
        "cyan": "spectrum:block/cyan_log_top",
        "light_blue": "spectrum:block/light_blue_log_top",
        "blue": "spectrum:block/blue_log_top",
        "purple": "spectrum:block/purple_log_top",
        "magenta": "spectrum:block/magenta_log_top",
        "pink": "spectrum:block/pink_log_top"
    },
    "log_side": {
        "weeping_gala": "spectrum:block/weeping_gala_log",
        "slate_noxwood": "spectrum:block/slate_noxcap_stem",
        "chestnut_noxwood": "spectrum:block/chestnut_noxcap_stem",
        "ivory_noxwood": "spectrum:block/ivory_noxcap_stem",
        "ebony_noxwood": "spectrum:block/ebony_noxcap_stem",
        "white": "spectrum:block/white_log",
        "light_gray": "spectrum:block/light_gray_log",
        "gray": "spectrum:block/gray_log",
        "black": "spectrum:block/black_log",
        "brown": "spectrum:block/brown_log",
        "red": "spectrum:block/red_log",
        "orange": "spectrum:block/orange_log",
        "yellow": "spectrum:block/yellow_log",
        "lime": "spectrum:block/lime_log",
        "green": "spectrum:block/green_log",
        "cyan": "spectrum:block/cyan_log",
        "light_blue": "spectrum:block/light_blue_log",
        "blue": "spectrum:block/blue_log",
        "purple": "spectrum:block/purple_log",
        "magenta": "spectrum:block/magenta_log",
        "pink": "spectrum:block/pink_log"
    },
    "stripped_log_top": {
        "weeping_gala": "spectrum:block/stripped_weeping_gala_log_top",
        "slate_noxwood": "spectrum:block/stripped_slate_noxcap_stem_top",
        "chestnut_noxwood": "spectrum:block/stripped_chestnut_noxcap_stem_top",
        "ivory_noxwood": "spectrum:block/stripped_ivory_noxcap_stem_top",
        "ebony_noxwood": "spectrum:block/stripped_ebony_noxcap_stem_top",
        "white": "spectrum:block/stripped_white_log_top",
        "light_gray": "spectrum:block/stripped_light_gray_log_top",
        "gray": "spectrum:block/stripped_gray_log_top",
        "black": "spectrum:block/stripped_black_log_top",
        "brown": "spectrum:block/stripped_brown_log_top",
        "red": "spectrum:block/stripped_red_log_top",
        "orange": "spectrum:block/stripped_orange_log_top",
        "yellow": "spectrum:block/stripped_yellow_log_top",
        "lime": "spectrum:block/stripped_lime_log_top",
        "green": "spectrum:block/stripped_green_log_top",
        "cyan": "spectrum:block/stripped_cyan_log_top",
        "light_blue": "spectrum:block/stripped_light_blue_log_top",
        "blue": "spectrum:block/stripped_blue_log_top",
        "purple": "spectrum:block/stripped_purple_log_top",
        "magenta": "spectrum:block/stripped_magenta_log_top",
        "pink": "spectrum:block/stripped_pink_log_top"
    },
    "stripped_log_side": {
        "weeping_gala": "spectrum:block/stripped_weeping_gala_log",
        "slate_noxwood": "spectrum:block/stripped_slate_noxcap_stem",
        "chestnut_noxwood": "spectrum:block/stripped_chestnut_noxcap_stem",
        "ivory_noxwood": "spectrum:block/stripped_ivory_noxcap_stem",
        "ebony_noxwood": "spectrum:block/stripped_ebony_noxcap_stem",
        "white": "spectrum:block/stripped_white_log",
        "light_gray": "spectrum:block/stripped_light_gray_log",
        "gray": "spectrum:block/stripped_gray_log",
        "black": "spectrum:block/stripped_black_log",
        "brown": "spectrum:block/stripped_brown_log",
        "red": "spectrum:block/stripped_red_log",
        "orange": "spectrum:block/stripped_orange_log",
        "yellow": "spectrum:block/stripped_yellow_log",
        "lime": "spectrum:block/stripped_lime_log",
        "green": "spectrum:block/stripped_green_log",
        "cyan": "spectrum:block/stripped_cyan_log",
        "light_blue": "spectrum:block/stripped_light_blue_log",
        "blue": "spectrum:block/stripped_blue_log",
        "purple": "spectrum:block/stripped_purple_log",
        "magenta": "spectrum:block/stripped_magenta_log",
        "pink": "spectrum:block/stripped_pink_log"
    },
    "planks": {
        "weeping_gala": "spectrum:block/weeping_gala_planks",
        "slate_noxwood": "spectrum:block/slate_noxwood_planks",
        "chestnut_noxwood": "spectrum:block/chestnut_noxwood_planks",
        "ivory_noxwood": "spectrum:block/ivory_noxwood_planks",
        "ebony_noxwood": "spectrum:block/ebony_noxwood_planks",
        "white": "spectrum:block/white_planks",
        "light_gray": "spectrum:block/light_gray_planks",
        "gray": "spectrum:block/gray_planks",
        "black": "spectrum:block/black_planks",
        "brown": "spectrum:block/brown_planks",
        "red": "spectrum:block/red_planks",
        "orange": "spectrum:block/orange_planks",
        "yellow": "spectrum:block/yellow_planks",
        "lime": "spectrum:block/lime_planks",
        "green": "spectrum:block/green_planks",
        "cyan": "spectrum:block/cyan_planks",
        "light_blue": "spectrum:block/light_blue_planks",
        "blue": "spectrum:block/blue_planks",
        "purple": "spectrum:block/purple_planks",
        "magenta": "spectrum:block/magenta_planks",
        "pink": "spectrum:block/pink_planks"
    }
}

global.PASTEL_WOODS = {
    "planks": {
        "weeping_gala": "spectrum:weeping_gala_planks",
        "slate_noxwood": "spectrum:slate_noxwood_planks",
        "chestnut_noxwood": "spectrum:chestnut_noxwood_planks",
        "ivory_noxwood": "spectrum:ivory_noxwood_planks",
        "ebony_noxwood": "spectrum:ebony_noxwood_planks",
        "white": "spectrum:white_planks",
        "light_gray": "spectrum:light_gray_planks",
        "gray": "spectrum:gray_planks",
        "black": "spectrum:black_planks",
        "brown": "spectrum:brown_planks",
        "red": "spectrum:red_planks",
        "orange": "spectrum:orange_planks",
        "yellow": "spectrum:yellow_planks",
        "lime": "spectrum:lime_planks",
        "green": "spectrum:green_planks",
        "cyan": "spectrum:cyan_planks",
        "light_blue": "spectrum:light_blue_planks",
        "blue": "spectrum:blue_planks",
        "purple": "spectrum:purple_planks",
        "magenta": "spectrum:magenta_planks",
        "pink": "spectrum:pink_planks"
    },
    "slab": {
        "weeping_gala": "spectrum:weeping_gala_slab",
        "slate_noxwood": "spectrum:slate_noxwood_slab",
        "chestnut_noxwood": "spectrum:chestnut_noxwood_slab",
        "ivory_noxwood": "spectrum:ivory_noxwood_slab",
        "ebony_noxwood": "spectrum:ebony_noxwood_slab",
        "white": "spectrum:white_slab",
        "light_gray": "spectrum:light_gray_slab",
        "gray": "spectrum:gray_slab",
        "black": "spectrum:black_slab",
        "brown": "spectrum:brown_slab",
        "red": "spectrum:red_slab",
        "orange": "spectrum:orange_slab",
        "yellow": "spectrum:yellow_slab",
        "lime": "spectrum:lime_slab",
        "green": "spectrum:green_slab",
        "cyan": "spectrum:cyan_slab",
        "light_blue": "spectrum:light_blue_slab",
        "blue": "spectrum:blue_slab",
        "purple": "spectrum:purple_slab",
        "magenta": "spectrum:magenta_slab",
        "pink": "spectrum:pink_slab"
    },
    "stairs": {
        "weeping_gala": "spectrum:weeping_gala_stairs",
        "slate_noxwood": "spectrum:slate_noxwood_stairs",
        "chestnut_noxwood": "spectrum:chestnut_noxwood_stairs",
        "ivory_noxwood": "spectrum:ivory_noxwood_stairs",
        "ebony_noxwood": "spectrum:ebony_noxwood_stairs",
        "white": "spectrum:white_stairs",
        "light_gray": "spectrum:light_gray_stairs",
        "gray": "spectrum:gray_stairs",
        "black": "spectrum:black_stairs",
        "brown": "spectrum:brown_stairs",
        "red": "spectrum:red_stairs",
        "orange": "spectrum:orange_stairs",
        "yellow": "spectrum:yellow_stairs",
        "lime": "spectrum:lime_stairs",
        "green": "spectrum:green_stairs",
        "cyan": "spectrum:cyan_stairs",
        "light_blue": "spectrum:light_blue_stairs",
        "blue": "spectrum:blue_stairs",
        "purple": "spectrum:purple_stairs",
        "magenta": "spectrum:magenta_stairs",
        "pink": "spectrum:pink_stairs"
    },
    "log": {
        "weeping_gala": "spectrum:weeping_gala_log",
        "slate_noxwood": "spectrum:slate_noxcap_stem",
        "chestnut_noxwood": "spectrum:chestnut_noxcap_stem",
        "ivory_noxwood": "spectrum:ivory_noxcap_stem",
        "ebony_noxwood": "spectrum:ebony_noxcap_stem",
        "white": "spectrum:white_log",
        "light_gray": "spectrum:light_gray_log",
        "gray": "spectrum:gray_log",
        "black": "spectrum:black_log",
        "brown": "spectrum:brown_log",
        "red": "spectrum:red_log",
        "orange": "spectrum:orange_log",
        "yellow": "spectrum:yellow_log",
        "lime": "spectrum:lime_log",
        "green": "spectrum:green_log",
        "cyan": "spectrum:cyan_log",
        "light_blue": "spectrum:light_blue_log",
        "blue": "spectrum:blue_log",
        "purple": "spectrum:purple_log",
        "magenta": "spectrum:magenta_log",
        "pink": "spectrum:pink_log"
    },
    "stripped_log": {
        "weeping_gala": "spectrum:stripped_weeping_gala_log",
        "slate_noxwood": "spectrum:stripped_slate_noxcap_stem",
        "chestnut_noxwood": "spectrum:stripped_chestnut_noxcap_stem",
        "ivory_noxwood": "spectrum:stripped_ivory_noxcap_stem",
        "ebony_noxwood": "spectrum:stripped_ebony_noxcap_stem",
        "white": "spectrum:stripped_white_log",
        "light_gray": "spectrum:stripped_light_gray_log",
        "gray": "spectrum:stripped_gray_log",
        "black": "spectrum:stripped_black_log",
        "brown": "spectrum:stripped_brown_log",
        "red": "spectrum:stripped_red_log",
        "orange": "spectrum:stripped_orange_log",
        "yellow": "spectrum:stripped_yellow_log",
        "lime": "spectrum:stripped_lime_log",
        "green": "spectrum:stripped_green_log",
        "cyan": "spectrum:stripped_cyan_log",
        "light_blue": "spectrum:stripped_light_blue_log",
        "blue": "spectrum:stripped_blue_log",
        "purple": "spectrum:stripped_purple_log",
        "magenta": "spectrum:stripped_magenta_log",
        "pink": "spectrum:stripped_pink_log"
    },
    "wood": {
        "weeping_gala": "spectrum:weeping_gala_wood",
        "slate_noxwood": "spectrum:slate_noxcap_hyphae",
        "chestnut_noxwood": "spectrum:chestnut_noxcap_hyphae",
        "ivory_noxwood": "spectrum:ivory_noxcap_hyphae",
        "ebony_noxwood": "spectrum:ebony_noxcap_hyphae",
        "white": "spectrum:white_wood",
        "light_gray": "spectrum:light_gray_wood",
        "gray": "spectrum:gray_wood",
        "black": "spectrum:black_wood",
        "brown": "spectrum:brown_wood",
        "red": "spectrum:red_wood",
        "orange": "spectrum:orange_wood",
        "yellow": "spectrum:yellow_wood",
        "lime": "spectrum:lime_wood",
        "green": "spectrum:green_wood",
        "cyan": "spectrum:cyan_wood",
        "light_blue": "spectrum:light_blue_wood",
        "blue": "spectrum:blue_wood",
        "purple": "spectrum:purple_wood",
        "magenta": "spectrum:magenta_wood",
        "pink": "spectrum:pink_wood"
    },
    "stripped_wood": {
        "weeping_gala": "spectrum:stripped_weeping_gala_wood",
        "slate_noxwood": "spectrum:stripped_slate_noxcap_hyphae",
        "chestnut_noxwood": "spectrum:stripped_chestnut_noxcap_hyphae",
        "ivory_noxwood": "spectrum:stripped_ivory_noxcap_hyphae",
        "ebony_noxwood": "spectrum:stripped_ebony_noxcap_hyphae",
        "white": "spectrum:stripped_white_wood",
        "light_gray": "spectrum:stripped_light_gray_wood",
        "gray": "spectrum:stripped_gray_wood",
        "black": "spectrum:stripped_black_wood",
        "brown": "spectrum:stripped_brown_wood",
        "red": "spectrum:stripped_red_wood",
        "orange": "spectrum:stripped_orange_wood",
        "yellow": "spectrum:stripped_yellow_wood",
        "lime": "spectrum:stripped_lime_wood",
        "green": "spectrum:stripped_green_wood",
        "cyan": "spectrum:stripped_cyan_wood",
        "light_blue": "spectrum:stripped_light_blue_wood",
        "blue": "spectrum:stripped_blue_wood",
        "purple": "spectrum:stripped_purple_wood",
        "magenta": "spectrum:stripped_magenta_wood",
        "pink": "spectrum:stripped_pink_wood"
    },
}

global.AFC_WOOD_TYPES = [
    "baobab",
    "eucalyptus",
    "mahogany",
    "hevea",
    "tualang",
    "teak",
    "cypress",
    "fig",
    "ironwood",
    "ipe",
    "mahoe",
    "ginkgo",
    "beech",
    "araucaria"
]

global.OVERWORLD_WOOD_TYPES = [
    "acacia",
    "ash",
    "aspen",
    "birch",
    "blackwood",
    "chestnut",
    "douglas_fir",
    "hickory",
    "kapok",
    "mangrove",
    "maple",
    "oak",
    "palm",
    "pine",
    "rosewood",
    "sequoia",
    "spruce",
    "sycamore",
    "white_cedar",
    "willow",
    "baobab",
    "eucalyptus",
    "mahogany",
    "hevea",
    "tualang",
    "teak",
    "cypress",
    "fig",
    "ironwood",
    "ipe",
    "mahoe",
    "ginkgo",
    "beech",
    "araucaria"
]

global.TFC_WOOD_TYPES = [
    "acacia",
    "ash",
    "aspen",
    "birch",
    "blackwood",
    "chestnut",
    "douglas_fir",
    "hickory",
    "kapok",
    "mangrove",
    "maple",
    "oak",
    "palm",
    "pine",
    "rosewood",
    "sequoia",
    "spruce",
    "sycamore",
    "white_cedar",
    "willow"
]

global.WOOD_TYPE_TO_MOD = {
    "acacia": "tfc",
    "ash": "tfc",
    "aspen": "tfc",
    "birch": "tfc",
    "blackwood": "tfc",
    "chestnut": "tfc",
    "douglas_fir": "tfc",
    "hickory": "tfc",
    "kapok": "tfc",
    "mangrove": "tfc",
    "maple": "tfc",
    "oak": "tfc",
    "palm": "tfc",
    "pine": "tfc",
    "rosewood": "tfc",
    "sequoia": "tfc",
    "spruce": "tfc",
    "sycamore": "tfc",
    "white_cedar": "tfc",
    "willow": "tfc",
    "baobab": "afc",
    "eucalyptus": "afc",
    "mahogany": "afc",
    "hevea": "afc",
    "tualang": "afc",
    "teak": "afc",
    "cypress": "afc",
    "fig": "afc",
    "ironwood": "afc",
    "ipe": "afc",
    "mahoe": "afc",
    "ginkgo": "afc",
    "beech": "afc",
    "araucaria": "afc"
}

// To Be Removed
global.SPECTRUM_WOODS = [
    "chestnut",
    "ivory",
    "slate",
    "ebony",
    "weeping_gala"
]

// To Be Removed
global.NOXWOODS = [
    "chestnut",
    "ivory",
    "slate",
    "ebony",
    "chestnut_noxwood",
    "ivory_noxwood",
    "slate_noxwood",
    "ebony_noxwood"
]
