try{
console.info("Loot Tables loaded")


LootJS.modifiers((event) => {

    const ITEM_REPLACEMENTS = {
        "minecraft:iron_ingot": "tfc:metal/ingot/wrought_iron",
        "minecraft:copper_ingot": "tfc:metal/ingot/copper",
        "minecraft:gold_ingot": "tfc:metal/ingot/gold",
        "minecraft:lapis_lazuli": "tfc:ore/lapis_lazuli",
        "minecraft:emerald": "tfc:ore/emerald",
        "minecraft:coal": "tfc:ore/bituminous_coal",
        "minecraft:diamond": "tfc:ore/diamond",
        "minecraft:bread": "tfc:food/wheat_bread",
        "minecraft:wheat": "tfc:food/wheat",
        "minecraft:enchanted_book": "minecraft:book",
        "minecraft:bucket": "tfc:wooden_bucket",
        "minecraft:potato": "tfc:seeds/potato",
        "minecraft:carrot": "tfc:seeds/carrot",
        "minecraft:beetroot_seeds": "tfc:seeds/beet",
        "minecraft:melon_seeds": "tfc:seeds/melon",
        "minecraft:pumpkin_seeds": "tfc:seeds/pumpkin",
        "minecraft:wheat_seeds": "tfc:seeds/wheat",
        "minecraft:cocoa_beans": "firmalife:food/cocoa_beans",
        "minecraft:sugar_cane": "tfc:seeds/sugarcane",
        "minecraft:kelp": "tfc:plant/giant_kelp_flower",
        "minecraft:mangrove_propagule": "tfc:wood/sapling/mangrove",
        "minecraft:dark_oak_sapling": "tfc:wood/sapling/hickory",
        "minecraft:cherry_sapling": "afc:wood/sapling/fig",
        "minecraft:acacia_sapling": "tfc:wood/sapling/acacia",
        "minecraft:jungle_sapling": "tfc:wood/sapling/kapok",
        "minecraft:birch_sapling": "tfc:wood/sapling/birch",
        "minecraft:spruce_sapling": "afc:wood/sapling/cypress",
        "minecraft:oak_sapling": "tfc:wood/sapling/oak",
        "minecraft:moss_block": "quark:moss_paste",
        "minecraft:pumpkin": "tfc:pumpkin",
        "minecraft:apple": "tfc:food/red_apple",
        "minecraft:egg": "firmalife:food/pickled_egg",
        "minecraft:baked_potato": "tfc:food/baked_potato",
        "minecraft:raw_gold": "tfc:ore/rich_native_gold",
        "minecraft:raw_copper": "tfc:ore/rich_native_copper",
        "minecraft:raw_iron": "tfc:ore/rich_limonite",
        "minecraft:golden_sword": "tfc:metal/double_ingot/gold",
        "minecraft:golden_hoe": "tfc:metal/ingot/gold",
        "minecraft:golden_axe": "tfc:metal/double_ingot/gold",
        "minecraft:golden_shovel": "tfc:metal/ingot/gold",
        "minecraft:golden_pickaxe": "tfc:metal/sheet/gold",
        "minecraft:golden_helmet": "tfc:metal/sheet/gold",
        "minecraft:golden_chestplate": "tfc:metal/double_sheet/gold",
        "minecraft:golden_leggings": "tfc:metal/double_sheet/gold",
        "minecraft:golden_boots": "tfc:metal/double_ingot/gold",
        "minecraft:iron_sword": "tfc:metal/sword/wrought_iron",
        "minecraft:iron_hoe": "tfc:metal/hoe/wrought_iron",
        "minecraft:iron_axe": "tfc:metal/axe/wrought_iron",
        "minecraft:iron_shovel": "tfc:metal/shovel/wrought_iron",
        "minecraft:iron_pickaxe": "tfc:metal/pickaxe/wrought_iron",
        "minecraft:iron_helmet": "tfc:metal/helmet/wrought_iron",
        "minecraft:iron_chestplate": "tfc:metal/chestplate/wrought_iron",
        "minecraft:iron_leggings": "tfc:metal/leggings/wrought_iron",
        "minecraft:iron_boots": "tfc:metal/boots/wrought_iron",
        "farmersdelight:iron_knife": "tfc:metal/knife/wrought_iron",
        "minecraft:diamond_sword": "tfc:metal/sword/black_steel",
        "minecraft:diamond_hoe": "tfc:metal/hoe/black_steel",
        "minecraft:diamond_axe": "tfc:metal/axe/black_steel",
        "minecraft:diamond_shovel": "tfc:metal/shovel/black_steel",
        "minecraft:diamond_pickaxe": "tfc:metal/pickaxe/black_steel",
        "minecraft:diamond_helmet": "tfc:metal/helmet/black_steel",
        "minecraft:diamond_chestplate": "tfc:metal/chestplate/black_steel",
        "minecraft:diamond_leggings": "tfc:metal/leggings/black_steel",
        "minecraft:diamond_boots": "tfc:metal/boots/black_steel",
        "farmersdelight:diamond_knife": "tfc:metal/knife/black_steel",
        "corn_delight:corn_seeds": "tfc:seeds/maize",
        "corn_delight:corn": "tfc:food/maize",
        "minecraft:shears": "tfc:metal/shears/wrought_iron",
        "minecraft:fern": "tfc:plant/lady_fern",
        "minecraft:large_fern": "tfc:plant/king_fern",
        "minecraft:tall_grass": "tfc:plant/tall_fescue_grass",
        "minecraft:grass": "tfc:plant/switchgrass",
        "minecraft:sweet_berries": "tfc:food/bunchberry",
        "minecraft:rabbit": "tfc:food/rabbit",
        "minecraft:mutton": "tfc:food/mutton",
        "minecraft:chicken": "tfc:food/chicken",
        "minecraft:beef": "tfc:food/beef",
        "minecraft:tropical_fish": "tfc:food/tropical_fish",
        "minecraft:salmon": "tfc:food/salmon",
        "minecraft:cod": "tfc:food/cod",
        "minecraft:porkchop": "tfc:food/pork",
        "minecraft:cactus": "tfc:plant/barrel_cactus",
        "minecraft:cooked_porkchop": "tfc:food/cooked_pork",
        "minecraft:cooked_salmon": "tfc:food/cooked_salmon",
        "minecraft:cooked_cod": "tfc:food/cooked_cod",
        "minecraft:stone_pickaxe": "tfc:stone/shovel/metamorphic",
        "minecraft:stone_axe": "tfc:stone/axe/metamorphic",
        "minecraft:crimson_fungus": "farmersdelight:red_mushroom_colony",
        "minecraft:warped_fungus": "farmersdelight:brown_mushroom_colony",
        "minecraft:spruce_log": "afc:wood/log/cypress",
        "minecraft:spruce_planks": "afc:wood/planks/cypress",
        "minecraft:spruce_stairs": "afc:wood/planks/cypress_stairs",
        "minecraft:dark_oak_log": "tfc:wood/log/hickory",
        "minecraft:dark_oak_planks": "tfc:wood/planks/hickory",
        "minecraft:dark_oak_stairs": "tfc:wood/planks/hickory_stairs",
        "farmersdelight:tomato": "tfc:food/tomato",
        "farmersdelight:tomato_seeds": "tfc:seeds/tomato",
        "farmersdelight:cabbage": "tfc:food/cabbage",
        "farmersdelight:cabbage_seeds": "tfc:seeds/cabbage",
    }
    
    Object.keys(ITEM_REPLACEMENTS).forEach(key =>{
        event.addLootTypeModifier(LootType.CHEST).replaceLoot(Item.of(key), Item.of(ITEM_REPLACEMENTS[key]), true)
    })
})



} catch(e) {
    console.log(e)
}