/*
StartupEvents.registry("fluid", event =>{

    global.DYE_COLOURS.forEach(colour => {
        event.create(`glass/${colour}`, 'thin')
            .displayName(`Molten ${nameProcessing(colour)} Glass`)
            .tint(global.COLOUR_TO_HEX[colour])
            .bucketColor(global.COLOUR_TO_HEX[colour])
            .thickTexture(global.COLOUR_TO_HEX[colour])
            .noBucket()
            .noBlock()
            .tag("tfc:molten_metals")
            .tag("kubejs:molten_glass")
    })

    event.create("glass/clear", 'thin')
        .displayName("Molten Clear Glass")
        .tint(0xD4FBFB)
        .bucketColor(0xD4FBFB)
        .thickTexture(0xD4FBFB)
        .noBucket()
        .noBlock()
        .tag("tfc:molten_metals")
        .tag("kubejs:molten_glass")
    
    event.create("electrum", 'thick')
        .displayName("Electrum")
        .tint(0xFFF10F)
        .bucketColor(0xFFF10F)
        .thickTexture(0xFFF10F)
        .noBucket()
        .noBlock()
        .tag("tfc:molten_metals")
    
    event.create("aluminium", 'thick')
        .displayName("Aluminium")
        .tint(0xCDD6DA)
        .bucketColor(0xCDD6DA)
        .thickTexture(0xCDD6DA)
        .noBucket()
        .noBlock()
        .tag("tfc:molten_metals")

    event.create("shale_clay_slurry", 'thin')
        .displayName("Shale Clay Slurry")
        .tint(0x4E4664)
        .bucketColor(0x4E4664)
        .thinTexture(0x4E4664)
        .noBucket()
        .noBlock()

    event.create("filtered_shale_clay_slurry", 'thin')
        .displayName("Filtered Shale Clay Slurry")
        .tint(0x746D89)
        .bucketColor(0x746D89)
        .thinTexture(0x746D89)
        .noBucket()
        .noBlock()

    event.create("boiled_water")
        .bucketColor(0xB2E0FE)
        .thinTexture(0xB2E0FE)
        .displayName("Boiled Water")
        .noBlock()
    
    event.create("brew")
        .bucketColor(0x300C0B)
        .thinTexture(0x300C0B)
        .displayName("Brew")
        .noBlock().noBucket()
    
    event.create("garum")
        .bucketColor(0x321C0B)
        .thinTexture(0x321C0B)
        .displayName("Garum")
        .noBlock()
})*/