#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

		[types.wood_type.caupona]
			walnut = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.afc]
			baobab = true
			eucalyptus = true
			mahogany = true
			hevea = true
			tualang = true
			teak = true
			cypress = true
			fig = true
			ironwood = true
			ipe = true
			araucaria = true
			beech = true
			ginkgo = true
			mahoe = true

		[types.wood_type.burningblock]
			burnt = false

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.spectrum]
			ivory_noxwood = false
			slate_noxwood = false
			ebony_noxwood = false
			chestnut_noxwood = false
			black = false
			blue = false
			brown = false
			cyan = false
			gray = false
			green = false
			light_blue = false
			light_gray = false
			lime = false
			magenta = false
			orange = false
			pink = false
			purple = false
			red = false
			white = false
			yellow = false
			weeping_gala = false

		[types.leaves_type.caupona]
			walnut = false
			fig = false
			wolfberry = false

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.quark]
			ancient = false
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			yellow_blossom = false
			red_blossom = false

		[types.leaves_type.spectrum]
			weeping_gala = false
			nephrite_blossom = false
			spirit_sallow = false
			black = false
			blue = false
			brown = false
			cyan = false
			gray = false
			green = false
			light_blue = false
			light_gray = false
			lime = false
			magenta = false
			orange = false
			pink = false
			purple = false
			red = false
			white = false
			yellow = true

#Disables specific entries
[entries]

		[entries.wood_type.create]
			window = false
			window_pane = false

		[entries.wood_type.farmersdelight]
			cabinet = false

		[entries.wood_type.shutter]
			shutter = true

		[entries.wood_type.architects_palette]
			board_stairs = false
			railing = true
			board_slab = false
			boards = false
			board_wall = false

		[entries.wood_type.quark]
			vertical_planks = false
			post = false
			trapped_chest = false
			bookshelf = false
			chest = false
			stripped_post = false
			ladder = false
			hollow_log = false
			vertical_slab = false

		[entries.leaves_type.quark]
			hedge = false
			leaf_carpet = false
